[general]
name = "cutlass_gemm"

[torch]
src = [
  "torch-ext/torch_binding.cpp",
  "torch-ext/torch_binding.h"
]

[kernel.gemm]
cuda-capabilities = [ "7.0", "7.2", "7.5", "8.0", "8.6", "8.7", "8.9", "9.0" ]
src = [
  "gemm.cu",
]
depends = [ "torch", "cutlass_3_6" ]
