[general]
name = "relu"
universal = false

[torch]
src = [
    "torch-ext/torch_binding.cpp",
    "torch-ext/torch_binding.h",
]

[kernel.activation]
backend = "cuda"
depends = ["torch"]
src = ["relu_cuda/relu.cu"]
cuda-flags = [ "-DWHO_AM_I_IF_NOT_THE_CANARY" ]

[kernel.activation_rocm]
backend = "rocm"
rocm-archs = [
    "gfx906",
    "gfx908",
    "gfx90a",
    "gfx940",
    "gfx941",
    "gfx942",
    "gfx1030",
    "gfx1100",
    "gfx1101",
]
depends = ["torch"]
src = ["relu_cuda/relu.cu"]

[kernel.activation_xpu]
backend = "xpu"
depends = ["torch"]
src = ["relu_xpu/relu.cpp"]
sycl-flags = [ "-DWHO_AM_I_IF_NOT_THE_CANARY" ]
