name: "Check build variants"
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened] # trigger on PRs
  workflow_dispatch:

jobs:
  build:
    name: Check build variants
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Generate variants JSON
        run: nix eval --raw .#lib.allBuildVariantsJSON | nix run nixpkgs#jq > build-variants.json
      - name: Check if variants JSON was complete
        run: |
          if git diff --exit-code build-variants.json; then
            echo "✅ variants.json is complete"
          else
            echo "🛑 regenerate variants.json: nix eval --raw .#lib.allBuildVariantsJSON | nix run nixpkgs#jq > build-variants.json"
            exit 1
          fi
