name: Rust

on: [push, pull_request]

jobs:
  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Cargo fmt (kernel-abi-check)
        run: ( cd kernel-abi-check && cargo fmt --all -- --check )
      - name: Cargo fmt (build2cmake)
        run: ( cd build2cmake && cargo fmt --all -- --check )

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - name: Clippy (kernel-abi-check)
        run: ( cd kernel-abi-check && cargo clippy -- -D warnings )
      - name: Clippy (build2cmake)
        run: ( cd build2cmake && cargo clippy -- -D warnings )
